### PR TITLE
Fixing gi import warnings (#288)

### LINKED ISSUE #288: PyGIWarning: Notify was imported without specifying a version first.
Scudcloud is failing to start on my Fedora 23.  Here is the message seen on the command line:

``` bash
$ scudcloud 
/usr/share/scudcloud/lib/notifier.py:3: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
```

Relevant Code

``` python
from dbus.exceptions import DBusException
try:
    from gi.repository import Notify
except ImportError:
    import notify2
    Notify = None
```

Package info

```
$ rpm -qi scudcloud
Name        : scudcloud
Version     : 1.0.86
Release     : 1.fc23
Architecture: noarch
Install Date: Wed 28 Oct 2015 10:37:37 AM CDT
Group       : Applications/Internet
Size        : 286962
License     : MIT
Signature   : (none)
Source RPM  : scudcloud-1.0.86-1.fc23.src.rpm
Build Date  : Mon 26 Oct 2015 03:47:58 PM CDT
Build Host  : Lucious.stiegnet.homelinux.net
Relocations : (not relocatable)
URL         : https://github.com/raelgc/scudcloud/
Summary     : Non official desktop client for Slack
Description :
ScudCloud uses the QT library with Webkit to render the web version of
Slack, and enhances it by integrating the QWebkit-Native bridge to
improve desktop integration.  Features include:
* Multiple teams support
* Native system notifications
* Count of unread direct mentions at launcher/system tray icon
* Alert/wobbling on new messages
* Channels quick list (Unity only)
* Optional "Close to Tray"
```

python3-gobject-base package info:

```
$ rpm -qi python3-gobject-base 
Name        : python3-gobject-base
Version     : 3.18.0
Release     : 2.fc23
Architecture: x86_64
Install Date: Fri 23 Oct 2015 09:57:14 AM CDT
Group       : Unspecified
Size        : 1065381
License     : LGPLv2+ and MIT
Signature   : RSA/SHA256, Mon 19 Oct 2015 08:22:24 AM CDT, Key ID 32474cf834ec9cba
Source RPM  : pygobject3-3.18.0-2.fc23.src.rpm
Build Date  : Mon 19 Oct 2015 06:52:05 AM CDT
Build Host  : buildvm-08.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://live.gnome.org/PyGObject
Summary     : Python 3 bindings for GObject Introspection base package
Description :
This package provides the non-cairo specific bits of the GObject Introspection
library.
```

### PR DESCRIPTION
**Pull request by raelgc**
Fixes #288

### CODE REVIEW

**Comment by raelgc** [comment]
@immerrr Can you test if these changes will work on Ubuntu 12.04?

**Comment by immerrr** [comment]
1. it appears that the proper way of invoking `require_version` is `gi.require_version`, not `gi.repository.require_version`:

```
$ /usr/bin/python3 -c "from gi.repository import require_version"
ERROR:root:Could not find any typelib for require_version
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name require_version
$ /usr/bin/python3 -c "from gi import require_version"
```
1. notify is OK:

```
$ /usr/bin/python3 -c "from gi import require_version; print(require_version('Notify', '0.7'))"
None
```
1. Unity 7.0 is unavailable, only 5.0 works:

```
$ /usr/bin/python3 -c "from gi import require_version; print(require_version('Unity', '7.0'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 52, in require_version
    (namespace, version))
ValueError: Namespace Unity not available for version 7.0
$ /usr/bin/python3 -c "from gi import require_version; print(require_version('Unity', '5.0'))"
None
```

**Comment by raelgc** [comment]
@immerrr Thank you for the quick reply!

I tried first with `gi.require_version`, but on 16.04 I got this error: `NameError: name 'gi' is not defined`. So first importing the `require_version` worked.

But, unfortunately appears to not works in 12.04 (not sure in 14.04).

About Unity version: so, version is 5 for Ubuntu 12.04. Not sure if we add a complicated checking here or if we keep 12.04 in a separate branch.

**Comment by immerrr** [comment]
`NameError: name 'gi' is not defined` means you need to do `import gi` before doing `gi.require_version`.

**Comment by stieg** [comment]
Here is what I see on my Fedora box:

```
[stieg@Lucious scudcloud]$ python3 -m scudcloud 
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stieg/Devel/stieg/scudcloud/scudcloud/__main__.py", line 16, in <module>
    import scudcloud.scudcloud as sca
  File "/home/stieg/Devel/stieg/scudcloud/scudcloud/scudcloud.py", line 28, in <module>
    gi.require_version('Unity', '7.0')
  File "/usr/lib64/python3.4/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Unity not available
```

**Comment by raelgc** [comment]
Fixed in #254
